"""Table agent for extracting structured financial metrics from table evidence."""

from __future__ import annotations

import argparse
import json
import re
from decimal import Decimal
from pathlib import Path

from finevidence.data.table_parser import parse_number
from finevidence.indexing.table_retriever import DEFAULT_TABLE_CHUNKS_PATH, TableRetriever


METRIC_ALIASES = {
    "revenue": (
        r"\btotal revenue\b",
        r"\brevenue\b",
        r"\btotal net sales\b",
        r"\bnet sales\b",
    ),
    "gross_profit": (
        r"\btotal gross margin\b",
        r"\bgross margin\b",
        r"\bgross profit\b",
    ),
    "operating_income": (
        r"\boperating income\b",
    ),
    "net_income": (
        r"\bnet income\b",
    ),
    "operating_cash_flow": (
        r"\bnet cash provided by operating activities\b",
        r"\bcash generated by operating activities\b",
        r"\bcash provided by operating activities\b",
    ),
    "total_assets": (
        r"\btotal assets\b",
    ),
    "total_liabilities": (
        r"\btotal liabilities\b",
    ),
    "cash_and_cash_equivalents": (
        r"\bcash and cash equivalents\b",
        r"\bcash equivalents\b",
    ),
}

TREND_TERMS = {
    "past",
    "last",
    "three",
    "trend",
    "change",
    "changes",
    "over time",
    "过去",
    "三年",
    "变化",
    "趋势",
}


def _cell_text(value: object) -> str:
    text = "" if value is None else str(value)
    return re.sub(r"\s+", " ", text).strip()


def _json_value(number: Decimal) -> int | float:
    if number == number.to_integral_value():
        return int(number)
    return float(number)


def _extract_year(text: str) -> str | None:
    match = re.search(r"\b(20[0-9]{2})\b", text)
    return match.group(1) if match else None


def _is_noise_label(label: str) -> bool:
    return any(
        token in label
        for token in (
            "percentage",
            "percent",
            "%",
            "growth",
            "per share",
            "earnings per share",
            "remaining performance",
            "allocated",
        )
    )


def _row_label(row: list[str]) -> str:
    labels: list[str] = []
    for cell in row[:3]:
        text = _cell_text(cell)
        if not text:
            continue
        if re.fullmatch(r"[$()0-9,.\- ]+", text):
            continue
        if parse_number(text) is not None:
            continue
        if text not in labels:
            labels.append(text)
    return " ".join(labels).lower()


def _match_metric(label: str) -> str | None:
    if not label or _is_noise_label(label):
        return None
    for metric, patterns in METRIC_ALIASES.items():
        for pattern in patterns:
            if re.search(pattern, label):
                return metric
    return None


def infer_requested_metrics(question: str) -> set[str]:
    """Infer requested financial metrics from a question."""

    query = question.lower()
    metrics: set[str] = set()

    if "income statement" in query or "statement of operations" in query:
        metrics.update({"revenue", "gross_profit", "operating_income", "net_income"})
    if "gross margin" in query or "gross profit" in query or "毛利率" in query or "毛利" in query:
        metrics.update({"revenue", "gross_profit"})
    if "revenue" in query or "net sales" in query or "sales" in query or "收入" in query:
        metrics.add("revenue")
    if "operating income" in query or "经营利润" in query:
        metrics.add("operating_income")
    if "net income" in query or "净利润" in query:
        metrics.add("net_income")
    if "cash flow" in query or "operating cash" in query or "经营现金流" in query:
        metrics.add("operating_cash_flow")
    if "assets" in query or "资产" in query:
        metrics.add("total_assets")
    if "liabilities" in query or "负债" in query:
        metrics.add("total_liabilities")
    if "cash and cash equivalents" in query or "现金及现金等价物" in query:
        metrics.add("cash_and_cash_equivalents")

    return metrics or {"revenue", "gross_profit", "operating_income", "net_income"}


def infer_requested_periods(question: str, fiscal_year: int | None = None) -> set[str] | None:
    """Infer specific periods to keep; return None when trend context wants all periods."""

    query = question.lower()
    if any(term in query for term in TREND_TERMS):
        return None

    years = set(re.findall(r"\b20[0-9]{2}\b", question))
    if years:
        return years
    if fiscal_year is not None:
        return {str(fiscal_year)}
    return None


def _is_change_column(cell: str) -> bool:
    lowered = cell.lower()
    return any(token in lowered for token in ("change", "percent", "percentage", "%"))


def _column_years(table: dict, header_scan_rows: int = 6) -> dict[int, str]:
    years: dict[int, str] = {}
    for column_index, column in enumerate(table.get("columns", [])):
        column_text = _cell_text(column)
        if _is_change_column(column_text):
            continue
        year = _extract_year(column_text)
        if year:
            years[column_index] = year

    for row in table.get("rows", [])[:header_scan_rows]:
        for column_index, cell in enumerate(row):
            cell_text = _cell_text(cell)
            if _is_change_column(cell_text):
                continue
            year = _extract_year(cell_text)
            if year:
                years.setdefault(column_index, year)
    return years


def _candidate_rank(candidate: dict) -> tuple[float, float, float]:
    label = candidate.get("source_label", "")
    exact_bonus = 0.0
    if label.startswith("total "):
        exact_bonus += 3.0
    if label in {"revenue", "gross margin", "gross profit", "operating income", "net income"}:
        exact_bonus += 2.0
    core_bonus = float(len(candidate.get("source_core_metrics", [])))
    source_score = float(candidate.get("source_table_score", 0.0))
    return source_score, core_bonus, exact_bonus


def select_canonical_metrics(candidates: list[dict]) -> list[dict]:
    """Keep the best candidate for each metric and period."""

    best: dict[tuple[str, str, str, int], dict] = {}
    for candidate in candidates:
        key = (
            candidate["ticker"],
            candidate["metric"],
            candidate["period"],
            int(candidate["fiscal_year"]),
        )
        if key not in best or _candidate_rank(candidate) > _candidate_rank(best[key]):
            best[key] = candidate

    return sorted(
        best.values(),
        key=lambda item: (item["ticker"], item["metric"], item["period"], item["source_table_id"]),
    )


def extract_metrics_from_table(
    table: dict,
    requested_metrics: set[str],
    requested_periods: set[str] | None = None,
) -> list[dict]:
    """Extract requested metric candidates from one table record."""

    column_years = _column_years(table)
    records: list[dict] = []

    for row_index, row in enumerate(table.get("rows", [])):
        label = _row_label(row)
        metric = _match_metric(label)
        if metric is None or metric not in requested_metrics:
            continue

        for column_index, cell in enumerate(row):
            number = parse_number(_cell_text(cell))
            if number is None:
                continue

            period = column_years.get(column_index)
            if period is None:
                continue
            if requested_periods is not None and period not in requested_periods:
                continue

            records.append(
                {
                    "ticker": table["ticker"],
                    "fiscal_year": table["fiscal_year"],
                    "period": period,
                    "metric": metric,
                    "value": _json_value(number),
                    "unit": "as_reported",
                    "source_table_id": table["table_id"],
                    "source_table_score": table.get("score", 0.0),
                    "source_core_metrics": table.get("core_metrics", []),
                    "source_row_index": row_index,
                    "source_column_index": column_index,
                    "source_label": label,
                    "source_path": table.get("source_path"),
                }
            )

    return records


class TableAgent:
    """Deterministic table tool for financial metric extraction."""

    def __init__(self, table_retriever: TableRetriever) -> None:
        self.table_retriever = table_retriever

    @classmethod
    def from_processed(cls, table_path: str | Path = DEFAULT_TABLE_CHUNKS_PATH) -> "TableAgent":
        return cls(TableRetriever.from_jsonl(table_path))

    def run(
        self,
        question: str,
        ticker: str | None = None,
        fiscal_year: int | None = None,
        top_k: int = 5,
        metrics: set[str] | None = None,
    ) -> dict:
        """Retrieve relevant tables and extract requested metric records."""

        requested_metrics = metrics or infer_requested_metrics(question)
        requested_periods = infer_requested_periods(question, fiscal_year)
        tables = self.table_retriever.search(
            question,
            ticker=ticker,
            fiscal_year=fiscal_year,
            top_k=top_k,
        )

        candidates: list[dict] = []
        for table in tables:
            candidates.extend(extract_metrics_from_table(table, requested_metrics, requested_periods))

        canonical_metrics = select_canonical_metrics(candidates)
        return {
            "agent": "TableAgent",
            "question": question,
            "ticker": ticker,
            "fiscal_year": fiscal_year,
            "requested_metrics": sorted(requested_metrics),
            "requested_periods": sorted(requested_periods) if requested_periods else None,
            "tables_considered": [
                {
                    "table_id": table.get("table_id"),
                    "score": round(float(table.get("score", 0.0)), 4),
                    "core_metrics": table.get("core_metrics", []),
                }
                for table in tables
            ],
            "candidate_count": len(candidates),
            "metrics": canonical_metrics,
        }


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the TableAgent.")
    parser.add_argument("question", help="Question to extract table metrics for.")
    parser.add_argument("--ticker", default=None, help="Optional ticker filter, e.g. AAPL.")
    parser.add_argument("--year", type=int, default=None, help="Optional fiscal year filter.")
    parser.add_argument("--top-k", type=int, default=5, help="Number of tables to inspect.")
    parser.add_argument("--tables", default=DEFAULT_TABLE_CHUNKS_PATH, help="Path to table_chunks.jsonl.")
    args = parser.parse_args()

    agent = TableAgent.from_processed(args.tables)
    result = agent.run(args.question, ticker=args.ticker, fiscal_year=args.year, top_k=args.top_k)
    print(json.dumps(result, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
