"""Verifier agent that coordinates claim, numeric, and evidence checks."""

from __future__ import annotations

import argparse
import json

from finevidence.verification.claim_extractor import extract_claims
from finevidence.verification.citation_checker import check_citations
from finevidence.verification.evidence_verifier import verify_evidence_support
from finevidence.verification.numeric_verifier import verify_numeric_outputs


FAILED_NUMERIC_STATUSES = {"numeric_error"}
WARNING_NUMERIC_STATUSES = {"insufficient_data"}
FAILED_EVIDENCE_STATUSES = {"unsupported"}
WARNING_EVIDENCE_STATUSES = {"partially_supported", "ambiguous"}
FAILED_CITATION_STATUSES = {"missing_citation", "unknown_citation"}


class VerifierAgent:
    """Run the FinEvidence verification stack behind one agent interface."""

    def run(
        self,
        answer: str | None = None,
        calculations: list[dict] | None = None,
        facts: list[dict] | None = None,
        evidence: list[dict] | None = None,
        claims: list[dict] | None = None,
        extract_answer_claims: bool = True,
        require_citations: bool = False,
    ) -> dict:
        """Verify an answer against structured calculations, facts, and evidence.

        Args:
            answer: Final answer text generated by the workflow.
            calculations: Derived metric records from CalculatorAgent.
            facts: Raw metric facts from TableAgent.
            evidence: Retrieved evidence summaries or records.
            claims: Optional pre-extracted claims. If omitted, the agent extracts them.
            extract_answer_claims: Whether to fall back to answer-text claim extraction when
                no structured calculations or facts are present.
            require_citations: Whether structured facts and calculations must be cited.

        Returns:
            A unified verification report with extracted claims and sub-reports.
        """

        calculations = calculations or []
        facts = facts or []
        evidence = evidence or []
        claims = self._claims(
            answer=answer,
            calculations=calculations,
            facts=facts,
            claims=claims,
            extract_answer_claims=extract_answer_claims,
        )
        numeric_report = verify_numeric_outputs(
            calculations=calculations,
            facts=facts,
            answer=answer,
        )
        evidence_report = verify_evidence_support(
            claims=claims,
            calculations=calculations,
            facts=facts,
            evidence=evidence,
        )
        citation_report = check_citations(
            answer=answer,
            evidence=evidence,
            calculations=calculations,
            facts=facts,
            claims=claims,
            require_citations=require_citations,
        )
        status = self._overall_status(numeric_report, evidence_report, citation_report)
        warnings = self._warnings(status, numeric_report, evidence_report, citation_report)

        return {
            "agent": "VerifierAgent",
            "status": status,
            "claim_count": len(claims),
            "claims": claims,
            "numeric_report": numeric_report,
            "evidence_report": evidence_report,
            "citation_report": citation_report,
            "warnings": warnings,
        }

    def _claims(
        self,
        answer: str | None,
        calculations: list[dict],
        facts: list[dict],
        claims: list[dict] | None,
        extract_answer_claims: bool,
    ) -> list[dict]:
        if claims is not None:
            return claims
        if calculations or facts or extract_answer_claims:
            return extract_claims(
                answer=answer,
                calculations=calculations,
                facts=facts,
            )
        return []

    def _overall_status(self, numeric_report: dict, evidence_report: dict, citation_report: dict) -> str:
        numeric_status = numeric_report.get("status")
        evidence_status = evidence_report.get("status")
        citation_status = citation_report.get("status")

        if (
            numeric_status in FAILED_NUMERIC_STATUSES
            or evidence_status in FAILED_EVIDENCE_STATUSES
            or citation_status in FAILED_CITATION_STATUSES
        ):
            return "failed"
        if numeric_status in WARNING_NUMERIC_STATUSES or evidence_status in WARNING_EVIDENCE_STATUSES:
            return "warning"
        if (
            numeric_status == "not_applicable"
            and evidence_status == "not_applicable"
            and citation_status == "not_applicable"
        ):
            return "not_applicable"
        return "passed"

    def _warnings(self, status: str, numeric_report: dict, evidence_report: dict, citation_report: dict) -> list[str]:
        warnings: list[str] = []
        numeric_status = numeric_report.get("status")
        evidence_status = evidence_report.get("status")
        citation_status = citation_report.get("status")

        if numeric_status == "numeric_error":
            warnings.append("Numeric verifier found inconsistent values.")
        elif numeric_status == "insufficient_data":
            warnings.append("Numeric verifier could not fully check the answer.")

        if evidence_status == "unsupported":
            warnings.append("Evidence verifier found unsupported claims.")
        elif evidence_status == "partially_supported":
            warnings.append("Evidence verifier found only partial claim support.")
        elif evidence_status == "ambiguous":
            warnings.append("Evidence verifier could not strictly link claims to evidence.")

        if citation_status == "missing_citation":
            warnings.append("Citation checker found required source evidence that was not cited.")
        elif citation_status == "unknown_citation":
            warnings.append("Citation checker found citations that do not map to available evidence.")

        if status == "not_applicable" and not warnings:
            return []
        return warnings


def verify_payload(payload: dict) -> dict:
    """Verify a JSON-like orchestrator payload."""

    return VerifierAgent().run(
        answer=payload.get("answer"),
        calculations=payload.get("calculations", []),
        facts=payload.get("facts", []),
        evidence=payload.get("evidence", []),
        claims=payload.get("claims"),
        extract_answer_claims=payload.get("extract_answer_claims", True),
        require_citations=payload.get("require_citations", False),
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the FinEvidence VerifierAgent on a JSON payload.")
    parser.add_argument("payload", help="Path to a JSON file containing answer, evidence, and structured records.")
    args = parser.parse_args()

    with open(args.payload, "r", encoding="utf-8") as file:
        payload = json.load(file)
    print(json.dumps(verify_payload(payload), ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
